export const generateSWOTElements = () => {
  const baseId = `tmpl_${Date.now()}`;
  return [
    {
      id: `${baseId}_bg_strengths`,
      type: "rectangle",
      x: 100,
      y: 100,
      width: 340,
      height: 280,
      color: "#22c55e",
    },
    {
      id: `${baseId}_bg_weaknesses`,
      type: "rectangle",
      x: 460,
      y: 100,
      width: 340,
      height: 280,
      color: "#ef4444",
    },
    {
      id: `${baseId}_bg_opportunities`,
      type: "rectangle",
      x: 100,
      y: 400,
      width: 340,
      height: 280,
      color: "#3b82f6",
    },
    {
      id: `${baseId}_bg_threats`,
      type: "rectangle",
      x: 460,
      y: 400,
      width: 340,
      height: 280,
      color: "#f59e0b",
    },
    {
      id: `${baseId}_txt_strengths`,
      type: "text",
      x: 120,
      y: 120,
      fontSize: 20,
      text: "STRENGTHS",
      color: "#166534",
    },
    {
      id: `${baseId}_txt_weaknesses`,
      type: "text",
      x: 480,
      y: 120,
      fontSize: 20,
      text: "WEAKNESSES",
      color: "#991b1b",
    },
    {
      id: `${baseId}_txt_opportunities`,
      type: "text",
      x: 120,
      y: 420,
      fontSize: 20,
      text: "OPPORTUNITIES",
      color: "#1e3a8a",
    },
    {
      id: `${baseId}_txt_threats`,
      type: "text",
      x: 480,
      y: 420,
      fontSize: 20,
      text: "THREATS",
      color: "#b45309",
    },
    {
      id: `${baseId}_sticky_strengths`,
      type: "sticky",
      x: 120,
      y: 170,
      width: 140,
      height: 140,
      color: "#166534",
      text: "Fast native WebRTC video calls",
    },
    {
      id: `${baseId}_sticky_weaknesses`,
      type: "sticky",
      x: 480,
      y: 170,
      width: 140,
      height: 140,
      color: "#b91c1c",
      text: "Strict-mode permission races",
    },
    {
      id: `${baseId}_sticky_opportunities`,
      type: "sticky",
      x: 120,
      y: 470,
      width: 140,
      height: 140,
      color: "#2563eb",
      text: "Real-time sync on canvas",
    },
    {
      id: `${baseId}_sticky_threats`,
      type: "sticky",
      x: 480,
      y: 470,
      width: 140,
      height: 140,
      color: "#b45309",
      text: "High database memory overhead",
    },
  ];
};

export const generateKanbanElements = () => {
  const baseId = `tmpl_${Date.now()}`;
  return [
    {
      id: `${baseId}_bg_todo`,
      type: "rectangle",
      x: 100,
      y: 100,
      width: 230,
      height: 500,
      color: "#2563eb",
    },
    {
      id: `${baseId}_txt_todo`,
      type: "text",
      x: 120,
      y: 120,
      fontSize: 22,
      text: "TO DO",
      color: "#2563eb",
    },
    {
      id: `${baseId}_sticky_todo1`,
      type: "sticky",
      x: 120,
      y: 170,
      width: 190,
      height: 120,
      color: "#b45309",
      text: "Draft technical specs",
    },
    {
      id: `${baseId}_sticky_todo2`,
      type: "sticky",
      x: 120,
      y: 310,
      width: 190,
      height: 120,
      color: "#2563eb",
      text: "Refactor backend sockets",
    },
    {
      id: `${baseId}_bg_progress`,
      type: "rectangle",
      x: 360,
      y: 100,
      width: 230,
      height: 500,
      color: "#7c3aed",
    },
    {
      id: `${baseId}_txt_progress`,
      type: "text",
      x: 380,
      y: 120,
      fontSize: 22,
      text: "IN PROGRESS",
      color: "#7c3aed",
    },
    {
      id: `${baseId}_sticky_progress1`,
      type: "sticky",
      x: 380,
      y: 170,
      width: 190,
      height: 120,
      color: "#7c3aed",
      text: "Designing Figma mockups",
    },
    {
      id: `${baseId}_bg_done`,
      type: "rectangle",
      x: 620,
      y: 100,
      width: 230,
      height: 500,
      color: "#166534",
    },
    {
      id: `${baseId}_txt_done`,
      type: "text",
      x: 640,
      y: 120,
      fontSize: 22,
      text: "DONE",
      color: "#166534",
    },
    {
      id: `${baseId}_sticky_done1`,
      type: "sticky",
      x: 640,
      y: 170,
      width: 190,
      height: 120,
      color: "#166534",
      text: "Initial git initialization",
    },
  ];
};

export const generateMindmapElements = () => {
  const baseId = `tmpl_${Date.now()}`;
  return [
    {
      id: `${baseId}_center_circle`,
      type: "circle",
      cx: 450,
      cy: 300,
      r: 60,
      color: "#7c3aed",
    },
    {
      id: `${baseId}_center_txt`,
      type: "text",
      x: 410,
      y: 290,
      fontSize: 16,
      text: "Main Topic",
      color: "#7c3aed",
    },
    {
      id: `${baseId}_branch_a`,
      type: "sticky",
      x: 180,
      y: 120,
      width: 150,
      height: 100,
      color: "#2563eb",
      text: "Subtopic A",
    },
    {
      id: `${baseId}_branch_b`,
      type: "sticky",
      x: 580,
      y: 120,
      width: 150,
      height: 100,
      color: "#7c3aed",
      text: "Subtopic B",
    },
    {
      id: `${baseId}_branch_c`,
      type: "sticky",
      x: 180,
      y: 380,
      width: 150,
      height: 100,
      color: "#166534",
      text: "Subtopic C",
    },
    {
      id: `${baseId}_branch_d`,
      type: "sticky",
      x: 580,
      y: 380,
      width: 150,
      height: 100,
      color: "#b45309",
      text: "Subtopic D",
    },
    {
      id: `${baseId}_arrow_a`,
      type: "arrow",
      points: [390, 260, 310, 200],
      color: "#2563eb",
      strokeWidth: 3,
    },
    {
      id: `${baseId}_arrow_b`,
      type: "arrow",
      points: [510, 260, 590, 200],
      color: "#7c3aed",
      strokeWidth: 3,
    },
    {
      id: `${baseId}_arrow_c`,
      type: "arrow",
      points: [390, 340, 310, 400],
      color: "#166534",
      strokeWidth: 3,
    },
    {
      id: `${baseId}_arrow_d`,
      type: "arrow",
      points: [510, 340, 590, 400],
      color: "#b45309",
      strokeWidth: 3,
    },
  ];
};

export const generateRetroElements = () => {
  const baseId = `tmpl_${Date.now()}`;
  return [
    {
      id: `${baseId}_bg_well`,
      type: "rectangle",
      x: 100,
      y: 100,
      width: 230,
      height: 500,
      color: "#166534",
    },
    {
      id: `${baseId}_txt_well`,
      type: "text",
      x: 120,
      y: 120,
      fontSize: 18,
      text: "WHAT WENT WELL",
      color: "#166534",
    },
    {
      id: `${baseId}_sticky_well1`,
      type: "sticky",
      x: 120,
      y: 170,
      width: 190,
      height: 120,
      color: "#166534",
      text: "Collaboration worked well!",
    },
    {
      id: `${baseId}_bg_improve`,
      type: "rectangle",
      x: 360,
      y: 100,
      width: 230,
      height: 500,
      color: "#b91c1c",
    },
    {
      id: `${baseId}_txt_improve`,
      type: "text",
      x: 380,
      y: 120,
      fontSize: 18,
      text: "WHAT TO IMPROVE",
      color: "#b91c1c",
    },
    {
      id: `${baseId}_sticky_improve1`,
      type: "sticky",
      x: 380,
      y: 170,
      width: 190,
      height: 120,
      color: "#b91c1c",
      text: "Clarify requirements early",
    },
    {
      id: `${baseId}_bg_actions`,
      type: "rectangle",
      x: 620,
      y: 100,
      width: 230,
      height: 500,
      color: "#7c3aed",
    },
    {
      id: `${baseId}_txt_actions`,
      type: "text",
      x: 640,
      y: 120,
      fontSize: 18,
      text: "ACTION ITEMS",
      color: "#7c3aed",
    },
    {
      id: `${baseId}_sticky_action1`,
      type: "sticky",
      x: 640,
      y: 170,
      width: 190,
      height: 120,
      color: "#7c3aed",
      text: "Setup pre-planning meetings",
    },
  ];
};
